apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: firecrawl
    component: api
spec:
  ports:
  - port: 3002 # External port (adjust if $PORT was set differently in compose)
    targetPort: http # Refers to container port name in Deployment (3002)
    protocol: TCP
    name: http
  selector:
    app: firecrawl
    component: api
  type: LoadBalancer # Or NodePort, or ClusterIP if using Ingress 