apiVersion: v1
kind: ConfigMap
metadata:
  name: firecrawl-config
data:
  REDIS_URL: "redis://redis:6379" # Assuming redis service is named 'redis' in the 'firecrawl' namespace
  REDIS_RATE_LIMIT_URL: "redis://redis:6379" # Same as REDIS_URL
  PLAYWRIGHT_MICROSERVICE_URL: "http://playwright-service:3000/scrape" # Assuming playwright service is named 'playwright-service'
  USE_DB_AUTHENTICATION: "false" # Default or configure as needed
  POSTHOG_HOST: "https://app.posthog.com" # Default or configure as needed
  SUPABASE_URL: "" # Configure if needed
  SELF_HOSTED_WEBHOOK_URL: "" # Configure if needed
  LOGGING_LEVEL: "info" # Default or configure as needed
  SEARXNG_ENDPOINT: "" # Configure if needed
  SEARXNG_ENGINES: "google,bing" # Default or configure as needed
  SEARXNG_CATEGORIES: "general" # Default or configure as needed
  INTERNAL_PORT: "3002" # Default internal port for API
  PLAYWRIGHT_PORT: "3000" # Default port for Playwright service
  BLOCK_MEDIA: "true" # Default for playwright service 