apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  labels:
    app: firecrawl
    component: playwright-service
spec:
  ports:
  - port: 3000
    targetPort: http # Refers to the container port name in the Deployment
    name: http
  selector:
    app: firecrawl
    component: playwright-service
  type: ClusterIP # Internal service only 