apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: firecrawl
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: firecrawl
    component: redis
  type: ClusterIP # Internal service only 