apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app: firecrawl
    component: redis
spec:
  accessModes:
    - ReadWriteOnce # Suitable for a single Redis pod
  resources:
    requests:
      storage: 1Gi # Adjust size as needed
  # storageClassName: <your-storage-class> # Uncomment and specify if needed 